feature_size: 8192
num_classes: 32000
num_batch: 10
batch_size: 10
index_dim: 10
num_index_samples: 100
seed: 0
prior_scale: 1.
lr_init: 0.0001
lr_final: 0.0001
num_epoch: 100
noise_std: 0.1
epinet_hiddens: [2048,1024,2048]